### ISSUE TITLE
MicroframeworkNotBootstrappedError

### ISSUE THREAD

**Issue by acayseth** [typestack/microframework#16]
Application Shutdown

I get error if use `framework.shutdown()`

```bash
Application is crashed
Cannot shutdown microframework because its not bootstrappedyet.
```

**Comment by NoNameProvided** [comment]
Closing as this project is being deprecated. 

If you have been using this project as webserver please use [typetack/routing-controllers](https://github.com/typestack/routing-controllers) instead.
