### ISSUE TITLE
How to increase default body parser limit in Microframework

### ISSUE THREAD

**Issue by Koushik-Sarkar** [typestack/microframework#7]
Hi,

We need to send a large amount of data from POST request. However, after a certain limit, it is throwing an error "Error: request entity too large". It seems that body parser limit is set to a default value. 

Is there any way to increase that value?

Thanks

**Comment by NoNameProvided** [comment]
Closing as this project is being deprecated. 

If you have been using this project as webserver please use [typetack/routing-controllers](https://github.com/typestack/routing-controllers) instead.
